name = "Physikercraft"
author = "ReTe"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d96a8726efa7af39569ef9963770e06a6c5bbed8a563f673bfde8bcd56c5ea29"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "kubejs/data/"
