name = "Physikercraft"
author = "ReTe"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "839e6b6ac4b415bd6d321f6a35f6ca1589b99e41470989b8f74d5d524b2402ee"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "kubejs/data/"
