name = "Physikercraft"
author = "ReTe"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b4802397062dd20054243781d634de5c430e451d1c942d338f48456433b668"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "kubejs/data/"
